service: minions-bgc

cors: true

resources:
  - ${file(resources/api-gateway-errors.yml)}

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: sa-east-1

  environment:
    TABELA_PRODUTOS: BGC-PRODUTOS
    TABELA_PEDIDOS: BGC-PEDIDOS

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:sa-east-1:*:*"

functions:
  create-produto:
    handler: Produtos/create.main
    events:
      - http:
          path: produtos
          method: post
          cors: true
          authorizer: aws_iam

  get-produto:
    handler: Produtos/get.main
    events:
      - http:
          path: produtos/{id}
          method: get
          cors: true
          authorizer: aws_iam

  list-produto:
    handler: Produtos/list.main
    events:
      - http:
          path: produtos
          method: get
          cors: true
          authorizer: aws_iam

  update-produto:
    handler: Produtos/update.main
    events:
      - http:
          path: produtos/{id}
          method: put
          cors: true
          authorizer: aws_iam

  delete-produto:
    handler: Produtos/delete.main
    events:
      - http:
          path: produtos/{id}
          method: delete
          cors: true
          authorizer: aws_iam
  
  create-pedido:
    handler: Pedidos/create.main
    events:
      - http:
          path: pedidos
          method: post
          cors: true
          authorizer: aws_iam

  get-pedido:
    handler: Pedidos/get.main
    events:
      - http:
          path: pedidos/{id}
          method: get
          cors: true
          authorizer: aws_iam

  list-pedido:
    handler: Pedidos/list.main
    events:
      - http:
          path: pedidos/{id}
          method: get
          cors: true
          authorizer: aws_iam

  update-pedido:
    handler: Pedidos/update.main
    events:
      - http:
          path: pedidos/{id}
          method: put
          cors: true
          authorizer: aws_iam

  delete-pedido:
    handler: Pedidos/delete.main
    events:
      - http:
          path: pedidos/{id}
          method: delete
          cors: true
          authorizer: aws_iam
